# Example GitHub Issue Form
name: "Bug Report"
description: "Submit a bug report for the Notfall system."
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        ## 🐞 Bug Report
        Please provide the details of the bug below. For related files, upload them as attachments in a comment after submitting this issue.
  - type: input
    id: title
    attributes:
      label: "Bug Title"
      description: "Provide a brief title for the bug."
      placeholder: "Enter a concise bug title here."
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "Provide detailed steps to reproduce the bug."
      placeholder: "1. Navigate to...\n2. Click on...\n3. Observe..."
  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected Behavior"
      description: "What did you expect to happen?"
      placeholder: "Describe the expected outcome here."
  - type: textarea
    id: actual_behavior
    attributes:
      label: "Actual Behavior"
      description: "What actually happened?"
      placeholder: "Describe what actually occurred."
  - type: dropdown
    id: severity
    attributes:
      label: "Bug Severity"
      description: "How severe is the impact of this bug?"
      options:
        - Low
        - Medium
        - High
        - Critical
  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Provide any additional information or context about the issue."
      placeholder: "Include logs, screenshots, or links to related files."
