name: "Request Contributor Access"
about: "Submit a request to become a contributor"
title: "Request Contributor Access"
labels: 
  - registration

body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in contributing! Please provide the following details to help us evaluate your request.

  - type: input
    id: github_username
    attributes:
      label: "Your GitHub Username"
      description: "Enter your GitHub username."

  - type: textarea
    id: reason
    attributes:
      label: "Why do you want to contribute?"
      description: "Briefly explain your interest in this project and how you plan to contribute."

  - type: dropdown
    id: area_of_interest
    attributes:
      label: "Contribution Area"
      description: "Select the area(s) you want to contribute to."
      options:
        - "Backend Development"
        - "Frontend Development"
        - "Documentation"
        - "Testing"
        - "Other"

  - type: dropdown
    id: experience_level
    attributes:
      label: "Experience Level"
      description: "Select your experience level."
      options:
        - "Beginner"
        - "Intermediate"
        - "Advanced"
        - "Expert"

  - type: input
    id: location
    attributes:
      label: "Your Location"
      description: "Provide your location for timezone considerations."

  - type: checkboxes
    id: guidelines
    attributes:
      label: "Contribution Guidelines Agreement"
      description: "Confirm that you have read and agree to the contribution guidelines."
      options:
        - label: "I have read and agree to the contribution guidelines."
          required: true
