# .github/ISSUE_TEMPLATE/request-contributor-access.yml

name: "Request Contributor Access" # The name of the issue template as displayed to users.
description: >
  Submit a request to become a contributor. Fill out the form below to provide your details and preferences. # A brief explanation of what the form is for.
labels: # Labels applied to the issue when submitted.
  - registration
  - contributor-request
  - onboarding

body: # The main content of the issue template.
  - type: markdown
    attributes:
      value: |
        ## 🌟 Welcome to Notfall Contributors!
        Thank you for your interest in contributing to the project. Please provide the requested details to help us evaluate your request.
        ### 🚀 What Happens Next?
        After submitting this form:
        - We'll review your request promptly.
        - You’ll receive further instructions or onboarding details if approved.
        - Feel free to reach out in the discussions or Slack for follow-ups.

  # Field: GitHub Username
  - type: input
    id: github_username
    attributes:
      label: "👤 GitHub Username" # Title for this input field.
      description: "Enter your GitHub username for collaboration and setup." # Clarifies the purpose of this input.
      placeholder: "YourGitHubUsername" # A hint for what the user should enter.

  # Field: Reason for Contributing
  - type: textarea
    id: reason
    attributes:
      label: "✨ Reason for Contributing"
      description: "Explain why you want to contribute and your goals." # Encourages users to share their motivation.
      placeholder: "I want to contribute because..." # A starting prompt for users.

  # Field: Preferred Contribution Area(s)
  - type: dropdown
    id: area_of_interest
    attributes:
      label: "📚 Preferred Contribution Area(s)"
      description: "Select the areas where you’d like to contribute. If unsure, select 'Other' and provide details below."
      options: # Possible areas where contributors can work.
        - Backend Development
        - Frontend Development
        - Documentation
        - Testing
        - UI/UX Design
        - Blockchain Integration
        - DevOps
        - Analytics and Reporting
        - Other

  # Field: Experience Level
  - type: dropdown
    id: experience_level
    attributes:
      label: "🎓 Experience Level"
      description: "Your level of expertise in your chosen contribution area(s)." # Helps us match tasks appropriately.
      options: # Levels of experience, with descriptions.
        - Beginner (Eager to learn)
        - Intermediate (Some experience)
        - Advanced (Independent contributor)
        - Expert (Mentor level)

  # Field: Location
  - type: input
    id: location
    attributes:
      label: "📍 Location"
      description: "Where are you based? This helps us coordinate effectively for meetings or collaborations." # Context for timezone considerations.
      placeholder: "City, Country (Timezone)" # Example input format.

  # Field: Weekly Hours Commitment
  - type: input
    id: hours_commitment
    attributes:
      label: "⏳ Weekly Hours Commitment"
      description: "How many hours can you contribute each week on average? This helps us assign tasks effectively." # Allows for realistic task assignments.
      placeholder: "e.g., 5-10 hours per week" # Example input format.

  # Field: Skills and Technologies
  - type: textarea
    id: skills
    attributes:
      label: "🛠️ Skills and Technologies"
      description: "List your technical skills, programming languages, tools, or technologies you’re proficient with." # Helps us understand your expertise.
      placeholder: "JavaScript, Python, MongoDB, React, Solidity, Spark, SQL, etc." # Example input format.

  # Field: Previous Contributions
  - type: textarea
    id: past_contributions
    attributes:
      label: "🔖 Previous Contributions"
      description: "Highlight any open-source projects, relevant work experience, or contributions to Notfall Contributors." # Encourages users to showcase their work.
      placeholder: "Mention past projects you've worked on." # Example input format.

  # Field: Goals and Expectations
  - type: textarea
    id: goals
    attributes:
      label: "🎯 Goals and Expectations"
      description: "What do you hope to achieve through your contributions? Any specific skills you'd like to develop?" # Captures the user's aspirations.
      placeholder: "e.g., Gain experience in full-stack development, learn about blockchain, etc." # Example goals.

  # Field: Contribution Guidelines Agreement
  - type: checkboxes
    id: guidelines_agreement
    attributes:
      label: "📜 Contribution Guidelines Agreement"
      description: "Please confirm that you have read and agree to follow the contribution guidelines."
      options: # Agreement confirmation checkbox.
        - label: "I have read and agree to the contribution guidelines."
          required: true # Ensures users must agree before submitting.

  # Field: Additional Details
  - type: textarea
    id: additional_details
    attributes:
      label: "💡 Additional Details"
      description: "Provide any other relevant information, preferences, or context about your request." # Allows for extra information.
      placeholder: "Include extra context, such as specific tasks or teams you’d like to join." # Example input format.
