name: Add Contributors

on:
  issues:
    types: [opened]

jobs:
  add-contributor:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the issue is a registration request
        uses: actions/github-script@v6
        id: check-registration
        with:
          script: |
            if (!context.payload.issue.labels.some(label => label.name === 'registration')) {
              return { approved: false };
            }
            return { approved: true, username: context.payload.issue.user.login };

      - name: Add user as a collaborator
        if: steps.check-registration.outputs.approved == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            const username = steps.check-registration.outputs.username;
            await github.repos.addCollaborator({
              owner: context.repo.owner,
              repo: context.repo.repo,
              username: username,
              permission: "write"
            });
            console.log(`User ${username} added as a contributor.`);

      - name: Comment on the issue
        if: steps.check-registration.outputs.approved == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            const username = steps.check-registration.outputs.username;
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              body: `Hi @${username}, your request to become a contributor has been approved! You now have write access to this repository.`
            });

      - name: Close the issue
        if: steps.check-registration.outputs.approved == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            await github.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              state: "closed",
            });
